# @package _group_
args:
    output_dir : "four-jukugo-gpt2"
    evaluation_strategy : "epoch"
    learning_rate : 2e-5
    weight_decay : 0.01
    save_steps : 100
    per_device_train_batch_size : 20
    num_train_epochs : 1
trainer_args:
   accelerator : "gpu"